site_name: Test Docs2
site_url: https://janosbabik.github.io/doc-test/
theme:
  name: material
  features:
    - navigation.top
  palette:
    primary: green
    accent: green
extra:
  version:
    provider: mike
    default: latest
