site_name: Test Docs2
site_url: https://janosbabik.github.io/doc-test/
theme:
  name: material
  features:
    - navigation.top
  palette:
    primary: deep orange
    accent: amber
extra:
  version:
    provider: mike
    alias: true
    default: stable
