name: Deploy LATEST DOCS
on:
  workflow_run:
    workflows: ["Bump version"]
    types:
      - completed
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Tag Name
        id: get_tag_name
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - name: Display Tag Name
        run: echo "The tag name is $TAG_NAME"
        
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material 
      - run: pip install mike
      - name: Build and Deploy
        working-directory: ./documentation
        run: |
          echo "GITHUB_REF_NAME=$GITHUB_REF_NAME"
          git fetch origin
          mike deploy --update-alias --push $GITHUB_REF_NAME latest
          mike set-default latest --push