name: Deploy LATEST DOCS
on:
  workflow_run:
    workflows: ["Bump version"]
    types:
      - completed
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - name: Set version
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material 
      - run: pip install mike
      - name: Build and Deploy
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        working-directory: ./documentation
        run: |
          git fetch origin
          mike deploy --update-alias --push $RELEASE_VERSION latest
          mike set-default latest --push